<?php

return [
    'site' => [
        'name' => env('APP_NAME', 'Snapic'),
        'slogan' => env('APP_SLOGAN', 'Premium creators sass social media platform.'),
        'description' => env('APP_DESCRIPTION', 'Snapic is a premium creators sass social media platform.'),
        'light_logo' => '/img/logo-black.png',
        'dark_logo' => '/img/logo-white.png',
        'favicon' => '/img/rounded-logo-gradient.svg',
        'currency_code' => 'BRL',
        'currency_symbol' => 'R$',
        'default_site_language' => 'pt',
        'allow_pwa_installs' => false,
    ],

    'admin' => [
        'icon_image' => '/img/rounded-logo-white.svg',
    ],

    'feed' => [
        'feed_posts_per_page' => 3,
        'feed_responsive_media' => 'responsive',
        'feed_suggestions_total_cards' => 3,
        'feed_suggestions_card_per_page' => 3,
    ],

    'homepage' => [
        'homepage_type' => 'landing',
    ],

    'media' => [
        'allowed_file_extensions' => 'png,jpg,jpeg,wav,mp4,mp3',
        'max_file_upload_size' => 3,
    ],


    'env' => env('APP_ENV', 'production'),
    'debug' => (bool) env('APP_DEBUG', false),
    'url' => env('APP_URL', 'http://localhost'),
    'asset_url' => env('ASSET_URL', null),
    'timezone' => 'UTC',
    'locale' => 'pt',
    'fallback_locale' => 'pt',
    'faker_locale' => 'en_US',
    'key' => env('APP_KEY'),
    'cipher' => 'AES-256-CBC',

    'providers' => [
        Illuminate\Auth\AuthServiceProvider::class,
        Illuminate\Broadcasting\BroadcastServiceProvider::class,
        Illuminate\Bus\BusServiceProvider::class,
        Illuminate\Cache\CacheServiceProvider::class,
        Illuminate\Foundation\Providers\ConsoleSupportServiceProvider::class,
        Illuminate\Cookie\CookieServiceProvider::class,
        Illuminate\Database\DatabaseServiceProvider::class,
        Illuminate\Encryption\EncryptionServiceProvider::class,
        Illuminate\Filesystem\FilesystemServiceProvider::class,
        Illuminate\Foundation\Providers\FoundationServiceProvider::class,
        Illuminate\Hashing\HashServiceProvider::class,
        Illuminate\Mail\MailServiceProvider::class,
        Illuminate\Notifications\NotificationServiceProvider::class,
        Illuminate\Pagination\PaginationServiceProvider::class,
        Illuminate\Pipeline\PipelineServiceProvider::class,
        Illuminate\Queue\QueueServiceProvider::class,
        Illuminate\Redis\RedisServiceProvider::class,
        Illuminate\Auth\Passwords\PasswordResetServiceProvider::class,
        Illuminate\Session\SessionServiceProvider::class,
        Illuminate\Translation\TranslationServiceProvider::class,
        Illuminate\Validation\ValidationServiceProvider::class,
        Illuminate\View\ViewServiceProvider::class,
        App\Providers\AppServiceProvider::class,
        App\Providers\AuthServiceProvider::class,
        App\Providers\BroadcastServiceProvider::class,
        App\Providers\EventServiceProvider::class,
        App\Providers\RouteServiceProvider::class,
        App\Providers\InstallerServiceProvider::class,
        App\Providers\PostsHelperServiceProvider::class,
        App\Providers\SettingsServiceProvider::class,
        App\Providers\ListsHelperServiceProvider::class,
        App\Providers\IconsServiceProvider::class,
        App\Providers\EmailsServiceProvider::class,
    ],

    'aliases' => [
        'App' => Illuminate\Support\Facades\App::class,
        'Arr' => Illuminate\Support\Arr::class,
        'Artisan' => Illuminate\Support\Facades\Artisan::class,
        'Auth' => Illuminate\Support\Facades\Auth::class,
        'Blade' => Illuminate\Support\Facades\Blade::class,
        'Broadcast' => Illuminate\Support\Facades\Broadcast::class,
        'Bus' => Illuminate\Support\Facades\Bus::class,
        'Cache' => Illuminate\Support\Facades\Cache::class,
        'Config' => Illuminate\Support\Facades\Config::class,
        'Cookie' => Illuminate\Support\Facades\Cookie::class,
        'Crypt' => Illuminate\Support\Facades\Crypt::class,
        'DB' => Illuminate\Support\Facades\DB::class,
        'Eloquent' => Illuminate\Database\Eloquent\Model::class,
        'Event' => Illuminate\Support\Facades\Event::class,
        'File' => Illuminate\Support\Facades\File::class,
        'Gate' => Illuminate\Support\Facades\Gate::class,
        'Hash' => Illuminate\Support\Facades\Hash::class,
        'Lang' => Illuminate\Support\Facades\Lang::class,
        'Log' => Illuminate\Support\Facades\Log::class,
        'Mail' => Illuminate\Support\Facades\Mail::class,
        'Notification' => Illuminate\Support\Facades\Notification::class,
        'Password' => Illuminate\Support\Facades\Password::class,
        'Queue' => Illuminate\Support\Facades\Queue::class,
        'Redirect' => Illuminate\Support\Facades\Redirect::class,
        'Redis' => Illuminate\Support\Facades\Redis::class,
        'Request' => Illuminate\Support\Facades\Request::class,
        'Response' => Illuminate\Support\Facades\Response::class,
        'Route' => Illuminate\Support\Facades\Route::class,
        'Schema' => Illuminate\Support\Facades\Schema::class,
        'Session' => Illuminate\Support\Facades\Session::class,
        'Storage' => Illuminate\Support\Facades\Storage::class,
        'Str' => Illuminate\Support\Str::class,
        'URL' => Illuminate\Support\Facades\URL::class,
        'Validator' => Illuminate\Support\Facades\Validator::class,
        'View' => Illuminate\Support\Facades\View::class,
        'Debugbar' => Barryvdh\Debugbar\Facade::class,
        'Markdown' => GrahamCampbell\Markdown\Facades\Markdown::class,
        'PaymentsProvider' => App\Providers\PaymentsServiceProvider::class,
        'PostsHelper' => App\Providers\PostsHelperServiceProvider::class,
        'ListsHelper' => App\Providers\ListsHelperServiceProvider::class,
        'AttachmentHelper' => App\Providers\AttachmentServiceProvider::class,
        'NotificationsHelper' => App\Providers\NotificationServiceProvider::class,
        'IconsHelper' => App\Providers\IconsServiceProvider::class,
        'InstallerHelper' => App\Providers\InstallerServiceProvider::class,
        'AppEmails' => App\Providers\EmailsServiceProvider::class,
        'GenericHelper' => App\Providers\GenericHelperServiceProvider::class,
        'LocalesHelper' => App\Providers\LocalesServiceProvider::class,
        'StreamsHelper' => App\Providers\StreamsServiceProvider::class,
    ],

];
